spring:
  application:
    name: CadastroDeEstoque

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true

CadastroDeEstoque:
  security:
    secret: "palavra-secreta"
